on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Utilisez la version LTS de Node.js
      - name: Install NPM packages
        run: npm ci
      - name: run build
        run: npm run build

  deploy:
    needs: build
    permissions:
      pages: write
      contents: write
      pull-requests: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: gh-pages
          folder: ./www
          token: ${{ secrets.GITHUB_TOKEN }}